<div class="wrap">
    <h1></h1>
    <div class="amarkal-settings">
        <div class="amarkal-settings-header">
            <h1><?php echo $this->config['title']; ?></h1>
            <p><?php echo $this->config['subtitle']; ?></p>
        </div>
        <div class="amarkal-settings-body">
            <form method="post" id="amarkal-settings-form">
                <header>
                    <div class="amarkal-settings-search">
                        <input type="text" id="settings-search" placeholder="Search settings"/>
                        <div class="dashicons dashicons-search"></div>
                    </div>
                    <p id="settings-search-results"></p>
                </header>
                <div id="amarkal-settings-notices"></div>
                <?php foreach($this->form->get_components() as $component): ?>
                    <div class="amarkal-settings-field" data-title="<?php echo $component->title ?>">
                        <div class="amarkal-settings-title">
                            <h3>
                                <?php echo $component->title ?>
                                <?php if($component->help): ?>
                                    <span class="help">
                                        ?<span class="help-content"><?php echo $component->help ?></span>
                                    </span>
                                <?php endif; ?>
                            </h3>
                            <?php if($component->description): ?>
                                <p class="description"><?php echo $component->description ?></p>
                            <?php endif; ?>
                        </div>
                        <div class="amarkal-settings-component">
                            <?php $component->render(true); ?>
                            <div class="amarkal-settings-error"></div>
                        </div>
                    </div>
                <?php endforeach; ?>
                <div id="amarkal-hidden-fields">
                    <?php wp_nonce_field(\Amarkal\Settings\RequestHandler::NONCE_ACTION,'_amarkal_settings_nonce'); ?>
                    <input type="hidden" name="_amarkal_settings_slug" value="<?php echo $this->config['slug']; ?>"/>
                    <input type="hidden" name="_amarkal_settings_parent_slug" value="<?php echo $this->config['parent_slug']; ?>"/>
                </div>
                <footer>
                    <div id="amarkal-settings-footer-html">
                        <?php echo $this->config['footer_html']; ?>
                    </div>
                    <button type="submit" value="reset" class="amarkal-settings-button secondary">Reset</button>
                    <button type="submit" value="save" class="amarkal-settings-button primary">Save</button>
                </footer>
            </form>
            <div class="amarkal-settings-description">
                <?php if(isset($this->config['description'])): ?>
                    <?php echo $this->config['description']; ?>
                <?php endif ?>
            </div>
        </div>
    </div>
    <?php echo $this->config['subfooter_html']; ?>
</div>